# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10my_service.proto\x12\x08tutorial\"/\n\x0bMathRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\n\n\x02op\x18\x03 \x01(\t\"\x1b\n\x0cMathResponse\x12\x0b\n\x03\x61ns\x18\x01 \x01(\t\"\x1b\n\nAnimeTitle\x12\r\n\x05title\x18\x01 \x01(\t\"[\n\x05\x41nime\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x10\n\x03sfw\x18\x03 \x01(\x08H\x00\x88\x01\x01\x12\x11\n\x04\x64\x61te\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x06\n\x04_sfwB\x07\n\x05_date\"L\n\x07Message\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x11\n\x04\x64\x61te\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_date\"\x13\n\x06Number\x12\t\n\x01x\x18\x01 \x01(\x03\x32\x8f\x02\n\x12JustAnotherService\x12=\n\nDoSomeMath\x12\x15.tutorial.MathRequest\x1a\x16.tutorial.MathResponse\"\x00\x12=\n\x10ListAnimeByTitle\x12\x14.tutorial.AnimeTitle\x1a\x0f.tutorial.Anime\"\x00\x30\x01\x12=\n\x11\x46loodWithMessages\x12\x11.tutorial.Message\x1a\x11.tutorial.Message\"\x00(\x01\x12<\n\x10SquareTheNumbers\x12\x10.tutorial.Number\x1a\x10.tutorial.Number\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MATHREQUEST._serialized_start=30
  _MATHREQUEST._serialized_end=77
  _MATHRESPONSE._serialized_start=79
  _MATHRESPONSE._serialized_end=106
  _ANIMETITLE._serialized_start=108
  _ANIMETITLE._serialized_end=135
  _ANIME._serialized_start=137
  _ANIME._serialized_end=228
  _MESSAGE._serialized_start=230
  _MESSAGE._serialized_end=306
  _NUMBER._serialized_start=308
  _NUMBER._serialized_end=327
  _JUSTANOTHERSERVICE._serialized_start=330
  _JUSTANOTHERSERVICE._serialized_end=601
# @@protoc_insertion_point(module_scope)
